import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { tokens } from "../src/tokens";

/**
 * Emits the same token values in two forms so neither app hand-copies them:
 *  - tokens.css: CSS custom properties, `@import`ed by apps/web (Tailwind v4
 *    is CSS-first, no JS config to hook into).
 *  - tokens.cjs: plain CommonJS, `require()`d by apps/mobile's
 *    tailwind.config.js, which Node loads directly (no TS transpilation).
 *
 * Both outputs live in generated/, which is gitignored (see .gitignore's
 * `**\/generated/` rule) - run `pnpm generate:design-tokens` after cloning.
 */
const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = resolve(packageRoot, "generated");
mkdirSync(outDir, { recursive: true });

const css = `/* Generated by packages/design-tokens/scripts/build.ts - do not edit by hand. */
:root {
  --dt-color-ziemia: ${tokens.colors.ziemia};
  --dt-color-powierzchnia: ${tokens.colors.powierzchnia};
  --dt-color-tekst: ${tokens.colors.tekst};
  --dt-color-tekst-muted: ${tokens.colors.tekstMuted};
  --dt-color-primary: ${tokens.colors.primary};
  --dt-color-warning-1: ${tokens.colors.warning1};
  --dt-color-warning-2: ${tokens.colors.warning2};
  --dt-color-warning-3: ${tokens.colors.warning3};
  --dt-glow-day: ${tokens.glow.day};
  --dt-glow-dusk: ${tokens.glow.dusk};
  --dt-glow-night: ${tokens.glow.night};
  --dt-ease-out: ${tokens.easing.out};
}
`;
writeFileSync(resolve(outDir, "tokens.css"), css);

const cjs = `// Generated by packages/design-tokens/scripts/build.ts - do not edit by hand.
module.exports = ${JSON.stringify(tokens, null, 2)};
`;
writeFileSync(resolve(outDir, "tokens.cjs"), cjs);

// eslint-disable-next-line no-console
console.log(`Wrote ${outDir}/tokens.css and ${outDir}/tokens.cjs`);
