import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { tokens } from "../src/tokens";

/**
 * Emits the same token values in two forms so neither app hand-copies them:
 *  - tokens.css: CSS custom properties, `@import`ed by apps/web (Tailwind v4
 *    is CSS-first, no JS config to hook into).
 *  - tokens.cjs: plain CommonJS, `require()`d by apps/mobile's
 *    tailwind.config.js, which Node loads directly (no TS transpilation).
 *
 * Both outputs live in generated/, which is gitignored (see .gitignore's
 * `**\/generated/` rule) - run `pnpm generate:design-tokens` after cloning.
 */
const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = resolve(packageRoot, "generated");
mkdirSync(outDir, { recursive: true });

/**
 * camelCase -> kebab-case, so `tekstMuted` becomes `tekst-muted`.
 *
 * Digits are split too (`warning1` -> `warning-1`). Without that the generated
 * names drift from the ones already referenced in globals.css, and an
 * unresolved CSS custom property fails silently - the severity colours would
 * simply stop rendering with nothing to say why.
 */
function kebab(value: string): string {
  return value
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([a-zA-Z])(\d)/g, "$1-$2")
    .toLowerCase();
}

/**
 * Walks the token tree and emits one custom property per leaf, named after its
 * path: `colors.tekstMuted` -> `--dt-color-tekst-muted`.
 *
 * Derived rather than hand-written, because the previous version listed every
 * variable by hand - which meant a token added to tokens.ts silently never
 * reached the CSS, and nothing failed to tell you.
 */
function flatten(value: unknown, path: readonly string[] = []): string[] {
  if (typeof value === "string" || typeof value === "number") {
    return [`  --dt-${path.map(kebab).join("-")}: ${value};`];
  }
  if (value && typeof value === "object") {
    return Object.entries(value).flatMap(([key, child]) => flatten(child, [...path, key]));
  }
  return [];
}

// Group names that read better shortened in CSS. Also pins the prefixes that
// globals.css already references, so renaming a key in tokens.ts cannot
// silently orphan a variable.
const GROUP_PREFIX: Record<string, string> = { colors: "color", easing: "ease" };

const declarations = Object.entries(tokens)
  .flatMap(([group, value]) => flatten(value, [GROUP_PREFIX[group] ?? group]))
  .join("\n");

const css = `/* Generated by packages/design-tokens/scripts/build.ts - do not edit by hand. */
:root {
${declarations}
}
`;
writeFileSync(resolve(outDir, "tokens.css"), css);

const cjs = `// Generated by packages/design-tokens/scripts/build.ts - do not edit by hand.
module.exports = ${JSON.stringify(tokens, null, 2)};
`;
writeFileSync(resolve(outDir, "tokens.cjs"), cjs);

// eslint-disable-next-line no-console
console.log(`Wrote ${outDir}/tokens.css and ${outDir}/tokens.cjs`);
